[versions]
agp = "9.3.1"
# @keep this version because it is not used in a dependency declaration
android-compileSdk = "36"
# @keep this version because it is not used in a dependency declaration
android-minSdk = "24"
assertk = "0.28.1"
dokka = "2.2.0"
# @keep this is library java compatibility version
java-version = "17"
kotlin = "2.4.10"
kotlinx-binary-compatibility-validator = "0.18.1"
# @keep this is library kotlin compatibility version
kotlin-version = "2.3.0"
ktfmt-plugin = "0.27.0"
maven-publish-plugin = "0.37.0"
tapmoc-plugin = "0.4.2"
versions-catalogue-update-plugin = "1.1.1"

[libraries]
assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
compat-tapmoc = { id = "com.gradleup.tapmoc", version.ref = "tapmoc-plugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-api-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlinx-binary-compatibility-validator" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt-plugin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish-plugin" }
versions-catalogue-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "versions-catalogue-update-plugin" }
