# Main workflow for check PRs and merges

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: iosSimulatorArm64Test
            os: macos-latest
          - target: jvmTest
            os: ubuntu-latest
          - target: linuxX64Test
            os: ubuntu-latest
          - target: testDebugUnitTest
            os: ubuntu-latest
          - target: testReleaseUnitTest
            os: ubuntu-latest
          - target: jsTest
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/cache@v3
      with:
        path: |
          ~/.konan
        key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}

    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'zulu'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        # Only write to the cache for builds on the 'main' and 'release' branches. (Default is 'main' only.)
        # Builds on other branches will only read existing entries from the cache.
        cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/release' }}
        cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

    - name: Build with Gradle
      uses: gradle/gradle-build-action@ce999babab2de1c4b649dc15f0ee67e6246c994f
      with:
        arguments: ${{ matrix.target }}
